version: '3'
services:
  jenkins:
    privileged: true
    user: root
    build: .
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - /etc/arm-apps/data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

