version: '3'
services:
  jenkins:
    privileged: true
    user: root
    build: .
    ports:
      - 8082:8080
      - 50000:50000
    container_name: jenkins
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
    volumes:
      - /etc/arm-apps/data/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:9.6
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: admin852
    volumes:
      - /etc/arm-apps/data/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:8.7.1-community
    ports:
      - 9000:9000
      - 9092:9092
    networks:
      - jenkins
    environment:
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: admin852
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_UPDATECENTER_ACTIVATE: "false"
    links:
      - postgres
    depends_on: 
      - postgres

networks:
  jenkins:
    driver: bridge
